# GoogLeNet model and training hyperparameters

# Learning Parameters
n_epochs: 90 # def: 70 for  AlexNet, 90 for GoogLeNet
learning_rate: 0.005  # def: 0.01 for both AlexNet and GoogLeNet

# Weight Decay
weight_decay: 0.0002 # def: 0.0005 for AlexNet, 0.0002 for GoogLeNet

# Momentum
momentum: 0.9 # def: 0.9

# Model info
name: googlenet
input_width: 224 # def: 227 for AlexNet, 224 for GoogLeNet 
input_height: 224 # def: 227 for AlexNet, 224 for GoogLeNet 

n_softmax_out: 1000

batch_size: 32 # def: 128 # def: 128 for AlexNet, 32 for GoogleNet 

image_mean: img_mean

data: imagenet
# Directories
dir_head : /scratch/ilsvrc12/#/work/mahe6562/prepdata_1000cat_128b/   # base dir where hkl training data is kept
label_folder : /labels/  # 
mean_file : /misc/img_mean.npy   
train_folder: /train_hkl_b256_b_128/   #/hkl_data/  
val_folder: /val_hkl_b256_b_128/   
# Data
file_batch_size: 128 # def: choose according to the preprocessed hkl file size
